In [13]:
from pathlib import Path
import sys
import os
import pandas as pd

In [14]:
Project_DIR = Path.cwd().resolve()
if Project_DIR.name == "notebook":
    Project_DIR = Project_DIR.parent

Data_DIR = Project_DIR / "DATA"
df = pd.read_csv(Data_DIR / "dataset.csv", encoding="latin-1")
df.head()

  text_type                                               text
0      spam  naturally irresistible your corporate identity...
1      spam  the stock trading gunslinger fanny is merrill ...
2      spam  unbelievable new homes made easy im wanting to...
3      spam  4 color printing special request additional in...
4      spam  do not have money get software cds from here s...

In [15]:
df.shape

(20348, 2)

In [16]:
df.describe()

       text_type                                               text
count      20348                                              20348
unique         2                                              20334
top          ham  SPAM ALERT  ð  User:     Username: @DillyBu...
freq       14337                                                  8

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20348 entries, 0 to 20347
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text_type  20348 non-null  object
 1   text       20348 non-null  object
dtypes: object(2)
memory usage: 318.1+ KB

In [18]:
df.isna().sum()

text_type    0
text         0
dtype: int64

**EDA**

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 6))
sns.countplot(y="text_type", data=df, order=df["text_type"].value_counts().index)
plt.title("Distribution of Spam and Ham Messages")
plt.xlabel("Count")
plt.ylabel("Message Type")
plt.show()

ValueError: Could not interpret value `label` for `y`. An entry with this name does not appear in `data`.